# Generated by Django 2.0b1 on 2017-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('summary', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=4096)),
                ('isLink', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('world', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Role A', 'roleA'), ('Role B', 'roleB'), ('Role C', 'roleC'), ('Role D', 'roleD'), ('Role E', 'roleE')], max_length=1)),
                ('country', models.CharField(choices=[('Country A', 'countryA'), ('Country B', 'countryB'), ('Country C', 'countryC'), ('Country D', 'countryD')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorldNewsCenterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_center_name', models.CharField(max_length=255)),
            ],
        ),
    ]
