# Generated by Django 2.0b1 on 2017-10-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20171023_1747'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('NewsHub', '0002_auto_20171023_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserClass',
        ),
    ]
