# Generated by Django 2.0b1 on 2017-10-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0003_auto_20171023_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=128)),
                ('S', models.TextField()),
                ('E', models.TextField()),
                ('IsoS', models.TextField()),
                ('Iso', models.TextField()),
                ('Q', models.TextField()),
                ('I', models.TextField()),
                ('T', models.TextField()),
                ('Rec', models.TextField()),
                ('D', models.TextField()),
                ('V', models.TextField()),
                ('Rm', models.TextField()),
                ('N', models.TextField()),
                ('susc2exp', models.TextField()),
                ('exp2infec', models.TextField()),
                ('rec2susc', models.TextField()),
                ('exp2iso', models.TextField()),
                ('isoinfec2quar', models.TextField()),
                ('infec2rec', models.TextField()),
                ('rx2rec', models.TextField()),
                ('infec2rx', models.TextField()),
                ('quar2rx', models.TextField()),
                ('susc2rec', models.TextField()),
                ('infecquar2died', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'country data',
                'db_table': 'CountryData',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'role data',
                'db_table': 'RoleData',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('running', models.BooleanField(default=False)),
                ('lastday', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'world data',
                'db_table': 'WorldData',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='userclass',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='role',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='world',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='roledata',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsHub.WorldData'),
        ),
        migrations.AddField(
            model_name='countrydata',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsHub.WorldData'),
        ),
    ]
