# Generated by Django 2.0b1 on 2017-10-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0004_auto_20171023_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldNewsCenterClass',
        ),
    ]
