# Generated by Django 2.0b1 on 2017-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0006_simulationgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationgame',
            name='game_link',
            field=models.URLField(blank=True),
        ),
    ]
