# Generated by Django 2.0b1 on 2017-10-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0007_simulationgame_game_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulationGame',
        ),
    ]
