# Generated by Django 2.0b1 on 2017-10-24 16:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0008_delete_simulationgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='allowed_games',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Poverty Simulation', 'Poverty Simulation'), ('The Louisiana Coastal Resilience Game', 'The Louisiana Coastal Resilience Game'), ('The UVA Bay Game®', 'The UVA Bay Game®'), ('The Global Health Security Game', 'The Global Health Security Game')], default=1, max_length=106),
            preserve_default=False,
        ),
    ]
