# Generated by Django 2.0b1 on 2017-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0009_userclass_allowed_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='world',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
