# Generated by Django 2.0b1 on 2017-10-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0013_auto_20171026_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='country',
            field=models.IntegerField(choices=[('158', 'country_A'), ('159', 'country_B'), ('160', 'country_C'), ('161', 'country_D')]),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='role',
            field=models.IntegerField(choices=[('1', 'Role A')]),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='world',
            field=models.IntegerField(choices=[('40', 'tempWorld')]),
        ),
    ]
