# Generated by Django 2.0b1 on 2017-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsHub', '0014_auto_20171026_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='country',
            field=models.CharField(choices=[('158', 'country_A'), ('159', 'country_B'), ('160', 'country_C'), ('161', 'country_D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='role',
            field=models.CharField(choices=[('1', 'Role A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='world',
            field=models.CharField(choices=[('40', 'tempWorld')], max_length=10),
        ),
    ]
