# Generated by Django 2.0b1 on 2017-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/media')),
                ('summary', models.CharField(max_length=1024)),
                ('game_link', models.URLField(blank=True)),
            ],
        ),
    ]
