# Generated by Django 2.0b1 on 2017-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLSGGameLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationgame',
            name='game_order',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
